# Site wide configuration

url: ""
host: 0.0.0.0

profile: true
future: true
show_drafts: true

google_site_verification: ""
bing_site_verification: ""
alexa_site_verification: ""
yandex_site_verification: ""

google_ad-client: ""
google_ad-slot: ""
google_analytics: ""
google_tagmanager: ""

reCaptcha:
  siteKey: ""
  secret: ""
