# Site wide configuration
source                   : .tmp/src
destination              : .tmp/dist

title                    : "DOMINIC REICH"
description              : "Personal website and blog of Dominic Reich. May contain photography and tech stuff."
logo                     : "/assets/images/android-chrome-384x384.png"
teaser                   : "/assets/images/default-teaser.png"
locale                   : "en_US"
words_per_minute         : 200

repository               : "freefallcid/dominicreich-jekyll"
url                      : "https://dominicreich.com"

social:
  name                   : "Dominic Reich"
  links:
    - "https://twitter.com/freefall0"
    - "https://github.com/freefallcid"
    - "https://500px.com/drtom"
    - "https://www.youtube.com/channel/UC8OnWO2vi6BWW0L5lBDfT7Q"
    - "https://plus.google.com/101846141042824192145"
    - "https://drtom0.myds.me/photo/"
    - "https://forum.xda-developers.com/member.php?u=3536148"

google_site_verification : "30eecSm8sH2itoI-l-N20wVDSk0Uw4Kg_NNuUC_mVBU"
bing_site_verification   : "4BEB54F647AEE7CE18D0A77137236FCB"
alexa_site_verification  : ""
yandex_site_verification : "d661d507bace53f0"

google_ad-client         : ""
google_ad-slot           : ""
#google_analytics         : "UA-90785047-4"
google_analytics         : ""
google_tagmanager        : "GTM-THWKCZV"

feed:
  path                  : "https://dominicreich.com/atom.xml"

favicon_version         : "9BPnoQEY43"

pingback_url            : "https://webmention.io/dominicreich.com/xmlrpc"
webmention_url          : "https://webmention.io/dominicreich.com/webmention"
micropub_url            : # "http://sitewriter.net/dominicreich.com/micropub"
microblog_url           : # "https://micro.blog/mmistakes"

# Site owner
author:
  name                   : "Dominic Reich"
  uri                    : &uri "https://dominicreich.com/about/"
  url                    : *uri
  bio                    : "An electrician that moved to the construction work side of life."
  picture                : "/assets/images/dominic-reich-selfie.jpg"
  twitter                : "https://twitter.com/freefall0"
  500px                  : "https://500px.com/drtom"
  photogallery           : "https://drtom0.myds.me/photo/#!Albums"
  #facebook               : "https://www.facebook.com/michaelrose"
  #instagram              : "https://www.instagram.com/drtom0/"
  #tumblr                 : "http://mademistakes.tumblr.com/"
  github                 : "https://github.com/freefallcid"
  google_plus            : "https://plus.google.com/101846141042824192145"
  xda                    : "https://forum.xda-developers.com/member.php?u=3536148"

twitter:
  username               : "freefall0"

# Staticman comments (full configuration in staticman.yml)
staticman:
  branch                 : "master"
  encrypted              : "XesI12jsaXJk4pIh5f3OYyhmUEUTQfH3BvAbBmAa24WAtZzEquFX4yqyH253xtociy6DirStIcWiZs/2iwSLdoVfqjLWvWZOPwSWFWKfZltfNJbPThmojl1NaBdWUdQR4EeUylyR81DDn8OlnwLy7r7G9CYcbmpxsNaBMNiuP4M="

# reCAPTCHA keys
reCaptcha:
  siteKey: "6Le-fz4UAAAAAO0Cp2XT0eTlwIqlNUBn1mPg9DXU"
  secret: "6Le-fz4UAAAAAK7FOeDfnbA2HEc5BYXU2JfIzAGJ"

# Jekyll configuration
permalink                : /:categories/:title/
lsi                      : true
future                   : false
show_drafts              : false
markdown                 : kramdown
kramdown:
  toc_levels             : 1..3
  input                  : GFM
  hard_wrap              : false
  auto_ids               : true
  entity_output          : as_char
  smart_quotes           : lsquo,rsquo,ldquo,rdquo
  enable_coderay         : false
highlighter              : rouge
strict_front_matter      : true
keep_files:
  - .git
include:
  - _pages
  - _redirects
  - _recipes
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - "*.sublime-project"
  - "*.sublime-workspace"
  - Capfile
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-typogrify
  - jekyll-figure
  - jekyll-algolia
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll-include-cache
  - jekyll-toc

# Collections
collections:
  faqs:
    output    : true
    permalink : /:collection/:path/
    title     : FAQs
  work:
    output    : true
    permalink : /:collection/:path/
    title     : Works
  recipes:
    output    : true
    permalink : /:collection/:path/
    title     : Recipes
  components:
    output    : false
  colors:
    output    : false

# Front Matter Defaults
defaults:
  # Blog Articles
  - scope:
      path: _posts/articles
      type: posts
    values:
      layout: post
      byline: true
      read_time: true
      comments: true
      support: true
      breadcrumbs:
        - label: "Blog articles"
          url: /articles/
  # Recipes
  - scope:
      path: _recipes
      type: recipes
    values:
      layout: post
      read_time: true
      comments: true
      support: false
      breadcrumbs:
        - label: "Recipes"
          url: /recipes/
  # Mastering Paper
  - scope:
      path: _posts/photography
      type: posts
    values:
      layout: post
      byline: true
      read_time: true
      comments: true
      support: true
      breadcrumbs:
        - label: "Photography"
          url: /work/photography/
      work: "Visual Artwork"
      seo:
        type: "CreativeWork"
  # Notes
  - scope:
      path: _posts/notes
      type: posts
    values:
      layout: post
      byline: true
      read_time: true
      breadcrumbs:
        - label: "Notes"
          url: /notes/
  # PaperFaces
  - scope:
      path: _posts/timelapse
      type: posts
    values:
      layout: post
      byline: true
      breadcrumbs:
        - label: "Timelapse videos"
          url: /work/timelapse/
      work: "Visual Artwork"
      seo:
        type: "CreativeWork"
  # Procreate Paintings
  - scope:
      path: _posts/software
      type: posts
    values:
      layout: post
      permalink: /work/:categories/:title/
      byline: true
      breadcrumbs:
        - label: "Works"
          url: /work/
        - label: "Software"
          url: /work/software/
      work: "Software development"
      seo:
        type: "CreativeWork"
#  # Tiny Paintings
#  - scope:
#      path: _posts/tiny-paintings
#      type: posts
#    values:
#      layout: post
#      byline: true
#      breadcrumbs:
#        - label: "Tiny Paintings"
#          url: /tiny-paintings/
#      work: "Illustration"
#      seo:
#        type: "CreativeWork"
  # Work (posts and collection)
  - scope:
      path: _posts/work
      type: posts
    values:
      layout: post
      breadcrumbs:
        - label: "Works"
          url: /work/
      seo:
        type: "CreativeWork"
  - scope:
      path: _work
      type: work
    values:
      layout: work
      category: work
      breadcrumbs:
        - label: "Works"
          url: /work/
      seo:
        type: "CreativeWork"
  # FAQs
  - scope:
      path: _faqs
      type: faqs
    values:
      layout: page
      read_time: true
      comments: true
      support: false
      breadcrumbs:
        - label: "Frequently asked questions"
          url: /faqs/
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: page
  # Drafts (because we have to define everything in there otherwise)
  - scope:
      path: _drafts
    values:
      layout: post
  - scope:
      path: admin
    values:
      sitemap: false

# Plugin: Pagination (jekyll-paginate-v2)
pagination:
  enabled: true
  debug: false
  per_page: 15
  permalink: "/page/:num/"
  title: ":title"
  limit: 0
  sort_field: "date"
  sort_reverse: true

# Plugin: Auto Pages (jekyll-paginate-v2)
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    enabled: true
    slugify:
      mode: raw
      cased: true
    layouts:
      - "autopage_tags.html"
    title: ":tag" # :tag is replaced by the tag name
    permalink: "/tag/:tag"

# Plugin: Table of Contents (jekyll-toc)
toc:
  min_level: 2
  max_level: 2
  list_class: "toc__menu"
  item_class: "toc__entry"
  item_prefix: "toc__"

# Plugin: Jekyll Algolia
algolia:
  application_id: RM5UBNYOIM
  index_name: dominicreich
  search_only_api_key: 76f79ffe28e10e3d95fbf8503a08f846
  nodes_to_index: "p,blockquote"
  files_to_exclude:
    - index.html
    - index.md
    - _pages/404.md
    - _pages/articles.md
    - _pages/faqs.md
    - _pages/mastering-paper.md
    - _pages/howto.md
    - _pages/portraits.md
    - _pages/sitemap.md
    - _pages/tag.md
    - _pages/notes.md
    - _pages/work.md
    - _pages/recipes.md
