# Site wide configuration
source: .tmp/src
destination: .tmp/dist

title: "DOMINIC REICH"
description: "Persönliche Webseite von Dominic Reich."
logo: &logo "/assets/images/android-chrome-384x384.png"
locale: "de_AT"
words_per_minute: 200

repository: "freefallcid/dominicreich-jekyll-2019"
url: "https://dominicreich.com"

social:
  name: "Dominic Reich"
  links:
    - "https://twitter.com/freefall0"
    - "https://github.com/freefallcid"
    - "https://www.youtube.com/channel/UC8OnWO2vi6BWW0L5lBDfT7Q"
    - "https://drtom0.myds.me/photo/"
    - "https://forum.xda-developers.com/member.php?u=3536148"
    - "https://www.reddit.com/user/cid85"

google_site_verification: "30eecSm8sH2itoI-l-N20wVDSk0Uw4Kg_NNuUC_mVBU"
bing_site_verification: "4BEB54F647AEE7CE18D0A77137236FCB"
alexa_site_verification: ""
yandex_site_verification: "d661d507bace53f0"

google_ad-client: ""
google_ad-slot: ""
#google_analytics: "UA-90785047-4"
google_analytics: ""
google_tagmanager: "GTM-THWKCZV"

feed:
  path: "https://dominicreich.com/atom.xml"

favicon_version: "9BPnoQEY44"

pingback_url: "https://webmention.io/dominicreich.com/xmlrpc"
webmention_url: "https://webmention.io/dominicreich.com/webmention"
#micropub_url: "https://mm-micropub-to-github.herokuapp.com/micropub/main"
#token_endpoint_url: "https://tokens.indieauth.com/token"
#authorization_endpoint_url: "https://indieauth.com/auth"
#microblog_url: "https://micro.blog/mmistakes"

# Site owner
author:
  name: "Dominic Reich"
  uri: &uri "https://dominicreich.com/ueber-mich/"
  url: *uri
  bio: "Elektriker, Schaler, Hobby-Admin, Möchtegernfotograf und -Bergsteiger."
  picture: "/assets/images/dominic-reich-selfie.jpg"
  twitter: "https://twitter.com/freefall0"
  photogallery: "https://drtom0.myds.me/photo/#!Albums"
  #facebook: "https://www.facebook.com/michaelrose"
  #instagram: "https://www.instagram.com/drtom0/"
  #tumblr: "http://mademistakes.tumblr.com/"
  github: "https://github.com/freefallcid"
  xda: "https://forum.xda-developers.com/member.php?u=3536148"
  reddit: "https://www.reddit.com/user/cid85"

twitter:
  username: "freefall0"

# Staticman comments (full configuration in staticman.yml)
staticman:
  branch: "master"

# reCAPTCHA keys
reCaptcha:
  siteKey: "6LfJvJcUAAAAAMDDZo-ZPz5wzzQizbZxYUb-jl77"
  secret: "RdgZ+HOKHkh9HAq4DF5NOf9aYG4Y36OFnoPlPyuHIN7O3kxgIfi/ssr98EFShn+jBEOQDfZW1zK+htBfYlJ5eZconJO6p7ZtLNFBaKTvC2myA2heN7yFFUrLTmBLj/eF85fKeLGQkcs7K2i0y3IdcCwqniC2a6EHTz8yrvOubes="

# Jekyll configuration
permalink: /:categories/:title/
lsi: true
future: false
show_drafts: false
markdown: kramdown
kramdown:
  toc_levels: 1..3
  input: GFM
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
highlighter: rouge
strict_front_matter: true
keep_files:
  - .git
include:
  - _pages
  - _redirects
  - _recipes
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .jekyll-cache
  - .sass-cache
  - "*.sublime-project"
  - "*.sublime-workspace"
  - Capfile
  - config
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - Gruntfile.js
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-typogrify
  - jekyll-figure
  - jekyll-algolia
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll-include-cache
  - jekyll-toc

# Collections
collections:
  faqs:
    output: false
    permalink: /:collection/:path/
    title: FAQs
  portfolio:
    output: true
    permalink: /:collection/:path/
    title: Portfolio
  recipes:
    output: true
    permalink: /:collection/:path/
    title: Rezepte
  components:
    output: false
  colors:
    output: false

# Front Matter Defaults
defaults:
  # Blog Articles
  - scope:
      path: _posts/artikel
      type: posts
    values:
      layout: post
      byline: false
      read_time: true
      comments: true
      support: true
      breadcrumbs:
        - label: "Blog Artikel"
          url: /artikel/
      image:
        facebook: *logo
        twitter: *logo
      twitter:
        card: summary
  # Recipes
  - scope:
      path: _recipes
      type: recipes
    values:
      layout: post
      read_time: true
      comments: true
      support: false
      breadcrumbs:
        - label: "Rezepte"
          url: /rezepte/
      image:
        facebook: *logo
        twitter: *logo
      twitter:
        card: summary
  # Mastering Paper
  - scope:
      path: _posts/fotografie
      type: posts
    values:
      layout: post
      byline: false
      read_time: true
      comments: true
      support: true
      breadcrumbs:
        - label: "Fotografie"
          url: /portfolio/fotografie/
      work: "Visual Artwork"
      seo:
        type: "CreativeWork"
      image:
        facebook: *logo
        twitter: *logo
      twitter:
        card: summary
  # Notes
  - scope:
      path: _posts/notizen
      type: posts
    values:
      layout: post
      byline: false
      read_time: true
      comments: true
      support: true
      breadcrumbs:
        - label: "Notizen"
          url: /notizen/
      image:
        facebook: *logo
        twitter: *logo
      twitter:
        card: summary
  # PaperFaces
  - scope:
      path: _posts/zeitraffer
      type: posts
    values:
      layout: post
      byline: false
      breadcrumbs:
        - label: "Zeitraffer-Videos"
          url: /portfolio/zeitraffer/
      work: "Visual Artwork"
      seo:
        type: "CreativeWork"
      image:
        facebook: *logo
        twitter: *logo
      twitter:
        card: summary
  # Procreate Paintings
  - scope:
      path: _posts/software
      type: posts
    values:
      layout: post
      permalink: /portfolio/:categories/:title/
      byline: false
      breadcrumbs:
        - label: "Portfolio"
          url: /portfolio/
        - label: "Software"
          url: /portfolio/software/
      work: "Software"
      seo:
        type: "CreativeWork"
      image:
        facebook: *logo
        twitter: *logo
      twitter:
        card: summary
#  # Tiny Paintings
#  - scope:
#      path: _posts/tiny-paintings
#      type: posts
#    values:
#      layout: post
#      byline: true
#      breadcrumbs:
#        - label: "Tiny Paintings"
#          url: /tiny-paintings/
#      work: "Illustration"
#      seo:
#        type: "CreativeWork"
  # Work (posts and collection)
  # - scope:
  #     path: _posts/work
  #     type: posts
  #   values:
  #     layout: post
  #     breadcrumbs:
  #       - label: "Works"
  #         url: /work/
  #     seo:
  #       type: "CreativeWork"
  - scope:
      path: _work
      type: work
    values:
      layout: work
      category: portfolio
      breadcrumbs:
        - label: "Portfolio"
          url: /portfolio/
      seo:
        type: "CreativeWork"
  - scope:
      path: _faqs
      type: faqs
    values:
      layout: page
      read_time: true
      comments: true
      support: false
      breadcrumbs:
        - label: "Häufig gestellte Fragen"
          url: /faqs/
      image:
        facebook: *logo
        twitter: *logo
      twitter:
        card: summary
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: page
      image:
        facebook: *logo
        twitter: *logo
      twitter:
        card: summary
  # Drafts (because we have to define everything in there otherwise)
  - scope:
      path: _drafts
    values:
      layout: post
  - scope:
      path: admin
    values:
      sitemap: false

# Plugin: Pagination (jekyll-paginate-v2)
pagination:
  enabled: true
  debug: false
  per_page: 15
  permalink: "/page/:num/"
  title: ":title"
  limit: 0
  sort_field: "date"
  sort_reverse: true

# Plugin: Auto Pages (jekyll-paginate-v2)
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    enabled: true
    slugify:
      mode: raw
      cased: true
    layouts:
      - "autopage_tags.html"
    title: ":tag" # :tag is replaced by the tag name
    permalink: "/tag/:tag"

# Plugin: Table of Contents (jekyll-toc)
toc:
  min_level: 2
  max_level: 2
  list_class: "toc__menu"
  item_class: "toc__entry"
  item_prefix: "toc__"

# Plugin: Jekyll Algolia
algolia:
  application_id: RM5UBNYOIM
  index_name: dominicreich
  search_only_api_key: 76f79ffe28e10e3d95fbf8503a08f846
  nodes_to_index: "p,blockquote"
  files_to_exclude:
    - index.html
    - index.md
    - _pages/404.md
    - _pages/articles.md
    - _pages/faqs.md
    - _pages/mastering-paper.md
    - _pages/howto.md
    - _pages/portraits.md
    - _pages/sitemap.md
    - _pages/tag.md
    - _pages/notes.md
    - _pages/work.md
    - _pages/recipes.md
